package main.java.org.htwg.konstanz.metaproject.communication;

public enum EmailTemplateType {

	METAPROJECT_LEADER_APPOINTMENT,

	PROJECT_LEADER_APPOINTMENT,

	TEAM_LEADER_APPOINTMENT,

	METAPROJECT_LEADER_CHANGE_COMMON,

	METAPROJECT_LEADER_CHANGE_NEW,

	METAPROJECT_LEADER_CHANGE_OLD,

	PROJECT_LEADER_CHANGE_COMMON,
	
	PROJECT_LEADER_CHANGE_NEW,
	
	PROJECT_LEADER_CHANGE_OLD,

	TEAM_LEADER_CHANGE_COMMON,
	
	TEAM_LEADER_CHANGE_NEW,
	
	TEAM_LEADER_CHANGE_OLD,

	TEAM_SEND_PRIO,

	ASSIGN_PROJECT_TO_TEAM,

	METAPROJECT_DELETE,

	PROJECT_DELETE_COMMON,
	
	PROJECT_DELETE_SPECIFIC,

	TEAM_DELETE_COMMON,
	
	TEAM_DELETE_SPECIFIC,

	TEAM_REMOVE_MEMBER_SPECIFIC,
	
	TEAM_REMOVE_MEMBER_COMMON,
	
	TEAM_REMOVE_MEMBER_LEADER,

	METAPROJECT_ADD_MEMBER,
	
	METAPROJECT_LEADER_ADD_TEAM_MEMBER,

	TEAM_INVITE,

	TEAM_REQUEST,
	
	TEAM_INVITATION_WITHDRAW,
	
	TEAM_APPLICATION_WITHDRAW,
	
	TEAM_INVITATION_REJECT,
	
	TEAM_INVITATION_ACCEPT,
	
	TEAM_APPLICATION_ACCEPT,
	
	TEAM_APPLICATION_REJECT

}
